### ISSUE TITLE
JS script “GoogleStreetView.js” does not work under 3.8.2

### ISSUE THREAD

**Issue by guenterw** [3liz/lizmap-javascript-scripts#81]
### What is the question? (in English)

In version 3.8.0-rc2 the JS script (GoogleStreetView.js) does not work.
Even the corresponding symbol for the position in the map does not appear. Instead, the pop-up window opens

![image](https://github.com/3liz/lizmap-web-client/assets/8373176/9bfb9595-08fe-4b5e-a5e5-518362e1a739)

Project "Test BürgerGIS 3.8.0 /Test WebGIS-Projekt Bauleitplanung' under https://cx21-8.webgis.biz

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.8.0-rc.2
* Lizmap plugin : 4.3.15
* QGIS Desktop : 3.34.7
* QGIS Server : 3.34.7
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.4.1
* QGIS Server plugin cadastre : 1.19.1
* QGIS Server plugin lizmap_server : 2.9.4
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : yes
* Number of parent : 2 folder(s)
* Prevent other drive : no
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 20.04

### Browsers

Chrome

### Browsers version

 125.0.6422.142

**Comment by josemvm** [comment]
hi @rldhont 
can you take a look at this script, please?
thanks in advance

**Comment by josemvm** [comment]
hi, i would really like to migrate my projects to LWC 3.8(.2) but without rehabilitating this script it is not possible for me
no errors appears in the browser console to try to debug the problem
can someone help me please?

thanks

**Comment by Gustry** [comment]
Hi @josemvm 

I'm sorry that the script is not compatible with LWC 3.8 but we had to add a disclaimer about this repository on the main readme.md : https://github.com/3liz/lizmap-javascript-scripts/blob/master/README.md#important-note-about-versions-contributions-and-maintainability We would be happy to find a technical solution for these "external" scripts, on which we do not have any control, tests, or development continuity.

>  can someone help me please?

Well, you can start by sharing the error it self. As usual, open your developper tools report any error, progress.

**Comment by Gustry** [comment]
In LWC 3.8.2, the user now invited to open its developper tools in case of error. This is of course not optimal, but better than nothing.

**Comment by nworr** [comment]
Quick code analysis : the openlayer map objet and Vector object are kind of OpenLayer 2
  
There's no error because  the ol2 map is no more visible since LizmpaWebClient 3.8, 

code should be refacto to use ol>2 classes

**Comment by josemvm** [comment]
> no errors appears in the browser console to try to debug the problem

@nworr thanks

hoping that someone with the right skills can adapt the code! ;-)

**Comment by guenterw** [comment]
@josemvm , I can only agree with that.
For me, this is also a knock-out criterion for the changeover with customer projects that are used to the function.

**Comment by Gustry** [comment]
Side note related to this situation :

> i would really like to migrate my projects to LWC 3.8(.2) but without rehabilitating this script it is not possible for me

> For me, this is also a knock-out criterion for the changeover with customer projects that are used to the function.

I know it's not the same, but it's kind of similar. A plugin hosted on https://plugins.qgis.org does not forward the responsibility to https://qgis.org to maintain the plugin. It's up to the plugin author to update, maintain or not this plugin.

Some of these scripts on this GIT repository have been :
* contributed by external contributors, maybe the script will not be maintained ? No one knows.
* made by 3Liz for a special customer, for its own project. Maybe it was for Lizmap Web Client 3.6 and 3Liz will not work on this script anymore

If you rely on these scripts, please consider funding, maybe an integration in core. So some unit tests can be added, to avoid regression in the future.

That's why we added this paragraph in the [readme.md](https://github.com/3liz/lizmap-javascript-scripts/blob/master/README.md#important-note-about-versions-contributions-and-maintainability). We were thinking quickly to rename this repository to `user-contributed-javascript` ? 
Anyway, thanks in advance for your testing on Lizmap Web Client.

**Comment by guenterw** [comment]
@Gustry, You are absolutely right!
I also wrote this from my own personal perspective (or that of my customers).
I'm happy to be convinced otherwise, but version 3.8 doesn't bring any real improvement over version 3.7 for my area of application. That's why we can continue to work well with the (very good) version 3.7.
For me, version 3.7 has the huge advantage of using QGIS themes compared to older versions.

But the comparison with QGIS is correct. There, too, I stayed with older versions because extensions no longer worked in the newer ones (especially when I switched to version 3). At some point, these were available again or you change your workflow or have to invest yourself as mentioned.
It's just very individual. Nevertheless, it is important and good that Lizmap is constantly evolving and uses the latest libraries. I am happy to support this with testing.

**Comment by cfsgarcia** [comment]
I have tweaked GoogleStreetView plugin to work with lizmap viewer 3.8.1 and later: 

https://github.com/cfsgarcia/lizmap-web-client/blob/master/3liz_plugins/GoogleStreetView.js

**Comment by Gustry** [comment]
Great, thanks. Can you provide a pull request? You. An update the existing file. And we can make a copy of the existing one by adding `_3_7` in the filename.

**Comment by mdouchin** [comment]
@cfsgarcia +1 please create a pull request with your changes, so that your work is integrated in this repository

**Comment by mdouchin** [comment]
I edited @Gustry previous comment (name of the files)

**Comment by Gustry** [comment]
Thanks @cfsgarcia, fixed in #88

**Comment by guenterw** [comment]
Thank you very much!
The StreetView display in the window works.
![image](https://github.com/user-attachments/assets/c8449829-cc75-40eb-a023-0f9f4e60073c)
https://cx21-8.webgis.biz/index.php/view/map?repository=buergergis8&project=bauleitplanung_3_8

Previously (in V3.7) you could still move the triangle on the map afterwards. I still can't do that in V3.8. Do I have to pay attention to something special or edit the js file accordingly?

The control works well via the Street View window.

It also works in 3.9 and 3.10, but here the pop-up window also opens:
https://cx21-9.webgis.biz/index.php/view/map?repository=buergergis9&project=bauleitplanung_3_9
https://cx21-10.webgis.biz/index.php/view/map?repository=buergergis9&project=bauleitplanung_3_10

**Comment by cfsgarcia** [comment]
You can drag and drop the marker around map. It may not be ovious enough though: when you hover the marker with the cursor of your mouse you should see a blue feature showing up in the center of the marker, that's the anchor that allows you to catch it and move it around. 
Then you're right, it seems like the mapclick event opening up popups still propagates. Will need a tweak.

**Comment by guenterw** [comment]
@cfsgarcia, thank you for your feedback.
Indeed. But you have to click on the marker first, then the blue circle appears and you can move it.
Without this short click, you only ever move the map.

**Comment by cfsgarcia** [comment]
The selection marker shows up whenever hovering at my end. I've tried in Chrome and Edge. What browsers are you using?

**Comment by guenterw** [comment]
behaves like this under the current Chrome, Firefox and Edge (Win10 64bit).
After placing the marker for the first time, no blue circle can be seen and it cannot be moved:
![image](https://github.com/user-attachments/assets/73b493d6-4801-4909-bb48-b92be090ebde)

After clicking on the marker, the blue circle is visible and can be moved:
![image](https://github.com/user-attachments/assets/ae29a000-5108-4517-b9a9-7d96dc6e1f29)

**Comment by cfsgarcia** [comment]
I've had a quick look at your app https://cx21-10.webgis.biz/index.php/view/map?repository=buergergis9&project=bauleitplanung_3_10.

It seems a bit messy in there. Switching to debugger mode, I can see both streeview plugins are present: old one and new one. Both calling initGoogleStreetView() funciton. Every method ends up being called twice. This may explain why it's dynsfunctioning. 

I suggest you ensure only the new plugin is used in that webapp, see if it helps.

**Comment by guenterw** [comment]
You are absolutely right. Thank you for pointing this out.
I renamed the new version and forgot to delete the old one. Sorry for the inconvenience. It also works fine in V3.9 and V3.10. Thank you very much.

**Comment by cfsgarcia** [comment]
I've also carried out a tweak to stop the popups from opening when dropping the streetview marker onto the map: https://github.com/3liz/lizmap-javascript-scripts/pull/90

**Comment by guenterw** [comment]
Thanks for the hint. I will test it.
I also wanted to test the display on tablet more closely.  On 11" Samsung the Google Street View window was very small. I may write another issue about this

**Comment by guenterw** [comment]
the current version ([#90](https://github.com/3liz/lizmap-javascript-scripts/pull/90)) does not work for me in 3.8, 3.9, 3.10. Maybe I am doing something wrong? See above for sample applications.
Could a version number be noted somewhere or have I just not seen it?

**Comment by cfsgarcia** [comment]
Oh yes my bad. A variable had an underscore. Different between my plugin and the one here in git.
Fixed here: https://github.com/3liz/lizmap-javascript-scripts/pull/91

**Comment by guenterw** [comment]
Without underscore it works in version 3.9 and 3.10. 
It also works in version 3.8, but you have to click on the symbol once to move it.

In all three versions, the symbol is not visible when raster data or WMS services are active.

Raster data:
![image](https://github.com/user-attachments/assets/ce51dbea-3cb0-4bae-b05a-703ef7dc65f4)

WMS service:
![image](https://github.com/user-attachments/assets/73108469-3994-47f6-a68a-59faf45128b3)

In version 3.7 it works with the triangle
![image](https://github.com/user-attachments/assets/430517c7-085e-4114-a28a-1a7bacfd1dd8)

**Comment by Gustry** [comment]
@cfsgarcia Please keep one PR opened. I will merge both, but one open PR is fine ;-) I was waiting for your signal on #91

**Comment by Gustry** [comment]
I have merged @cfsgarcia, thanks for your contributions ;-)

**Comment by cfsgarcia** [comment]
@Gustry sorry I may have created another PR. All the others seem to be closed. 
This PR https://github.com/3liz/lizmap-javascript-scripts/pull/93 may help framing GSV pano better when switching to media mode.

**Comment by josemvm** [comment]
GSV stop working under 3.8.4-pre, 8137, 2024-12-11

**Comment by josemvm** [comment]
![imagem](https://github.com/user-attachments/assets/0d20e21d-37e6-49c2-a751-015ee999b894)

**Comment by guenterw** [comment]
I can confirm that.
Both under 3.8.4-pre.8816 (05.12.) and under 3.8.4-pre.8140 (12.12.) only this appears, without any further function.

![image](https://github.com/user-attachments/assets/f353f45b-00fb-450e-b725-d4660fa04a59)

**Comment by rldhont** [comment]
@josemvm @guenterw can you open a new issue ?

**Comment by guenterw** [comment]
Unfortunately, the error also occurs with the current version 3.7.13.
(https://cx21-7.webgis.biz/index.php/view/map?repository=buergergis7&project=bauleitplanung_3_7)

In version 3.7.13-pre.7760 from 03.12.2024 it still works perfectly

**Comment by nboisteault** [comment]
Tests are running but you can apply those changes and tell us if it fix the bug : https://github.com/3liz/lizmap-web-client/pull/5130/commits/b61a55b7a04cd80cb2ed684a571680faa8944d07

**Comment by guenterw** [comment]
It works in version 3.8.4-pre.8154 (16.12.2024), but not yet in 3.7.14-pre.7788 (16.12.2024)

See above for examples

**Comment by nboisteault** [comment]
@guenterw I have just made a fix for 3.7. Thanks for your tests.

**Comment by guenterw** [comment]
@nboisteault Works in version 3.7.14-pre.7792 from 20.12.2024 - Thank you
